### ISSUE TITLE
Parts Missing from Craft files

### ISSUE THREAD

**Issue by Dadowinspace** [benjee10/HabTech2#10]
The ISS craft files won't load because they are missing the Canadarm. Is there a chance I am missing something? I can't see any installed mods that would affect the craft files. 
![Kerbal Space Program Screenshot 2023 02 23 - 13 09 21 26](https://user-images.githubusercontent.com/126197436/221006763-21d31b41-477e-4b6f-a8a2-a3ac2f2564c2.png)

Thank You

**Comment by benjee10** [comment]
You either don't have HabTechRobotics installed, or are using an old version of it bundled with another mod. The latest version of htRobotics is bundled with the HabTech release zip, or can be downloaded separately here: https://github.com/benjee10/htRobotics/releases

Let me know if the issue persists.

**Comment by Dadowinspace** [comment]
yeah it was an old version of robotics. thank you for the help and the update link
