### ISSUE TITLE
Feature request: Robotic truss for realistic ISS assembly

### ISSUE THREAD

**Issue by JacobB094** [benjee10/HabTech2#15]
An alternate setup that would divide solar truss parts in a realistic way, similar to old HabTech truss. SARJ would be a separate part that would work with either stock robotics or IRNext. 

Use of robotics in this role would allow separating the P5/S5 trusses into discrete parts and enabling surface attachment on the P6/S6, thus enabling robotic arms to handle the modules. If the structural parts of the trusses was also provided as a separate part, this would enable building a truss made only of rectangular pieces, in a manner similar to Freedom variant seen in ETS.

**Comment by JacobB094** [comment]
Going off the comment on the forum, I think that a whole family of rectangular truss pieces could be composed from bits the solar truss assemblies. This would be of great utility.

**Comment by benjee10** [comment]
Not possible unfortunately due to the complexity of the P6/S6 mesh and textures not allowing for it to be separated out easily, and partly down to the original files being lost in a hard drive failure making the entire operation even more complex.
