### ISSUE TITLE
ht2_Solar array duo bottom node issue

### ISSUE THREAD

**Issue by si2504** [benjee10/HabTech2#5]
An issue I'm experiencing is when using the bottom node of the solar array duo, it is causing explosions of the part. I cannot fathom what may be causing this. If I connect parts using the top node, this doesn't happen. I use a custom "rescaleFactor = 1.5625" for my RO configs and that's about the only thing that my RO config changes to the part. all other parts that have this rescaleFactor applied do not suffer this same issue.

**Comment by benjee10** [comment]
Closed as part has since been revamped
